const {
  BLOCK,
  TROUBLE,
  NONE,
} = require('../../../../../default-intelligence').dcmConfigModel.nodeDataType;

/**
 * @type {mDeviceMap}
 */
const map = {
  drawInfo: {
    frame: {
      // FIXME:
      mapInfo: {
        width: 4000,
        height: 5000,
        backgroundInfo: {
          backgroundData: '',
          backgroundPosition: [0, 0],
        },
      },
      svgModelResourceList: [
        // FIXME:
        {
          id: 'solarEvaporationBlock',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 700, color: '#abe3e1', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'normalEvaporationBlock_A',
          type: 'rect',
          elementDrawInfo: { width: 1930, height: 850, color: '#bd8f3a', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'normalEvaporationBlock_B',
          type: 'rect',
          elementDrawInfo: { width: 1930, height: 600, color: '#bd8f3a', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'normalCrystalizingBlock',
          type: 'rect',
          elementDrawInfo: { width: 500, height: 400, color: '#988224', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'reservoir_A',
          type: 'rect',
          elementDrawInfo: { width: 2600, height: 300, color: 'blue', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'reservoir_B',
          type: 'rect',
          elementDrawInfo: { width: 500, height: 300, color: 'blue', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'jago',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 300, color: 'skyblue', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'brineWarehouse_A',
          type: 'rect',
          elementDrawInfo: { width: 700, height: 200, color: '#90b4dd', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'brineWarehouse_B',
          type: 'rect',
          elementDrawInfo: { width: 490, height: 200, color: '#90b4dd', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'brineWarehouse_C',
          type: 'rect',
          elementDrawInfo: { width: 300, height: 200, color: '#90b4dd', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'brineWarehouse_D',
          type: 'rect',
          elementDrawInfo: { width: 270, height: 200, color: '#90b4dd', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'sea',
          type: 'rect',
          elementDrawInfo: { width: 3980, height: 100, color: 'skyblue', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'waterWay',
          type: 'line',
          elementDrawInfo: { width: 60, color: 'gray', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'peWaterWay',
          type: 'line',
          elementDrawInfo: { width: 60, color: '#108760', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // 주황
        {
          id: 'pipeLine_A',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#ff9a00', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // 파랑
        {
          id: 'pipeLine_B',
          type: 'line',
          elementDrawInfo: { width: 10, color: 'blue', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // 진보라
        {
          id: 'pipeLine_C',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#7513a1', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // 빨강
        {
          id: 'pipeLine_D',
          type: 'line',
          elementDrawInfo: { width: 10, color: 'red', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'waterDoor',
          type: 'rect',
          elementDrawInfo: { width: 80, height: 80, color: '#b45b95', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'valve',
          type: 'polygon',
          elementDrawInfo: { width: 30, height: 30, color: 'yellow', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // FIXME: 필요없지 않나? 있는지 모르겠다?
        {
          id: 'gateValve',
          type: 'polygon',
          elementDrawInfo: { width: 0, height: 0, color: '', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'overPump',
          type: 'circle',
          elementDrawInfo: { width: 80, height: 80, radius: 80, color: '#22fb00', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'underPump',
          type: 'circle',
          elementDrawInfo: { width: 60, height: 60, radius: 60, color: '#8b24b0', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        {
          id: 'output',
          type: 'circle',
          elementDrawInfo: { width: 25, height: 25, radius: 25, color: 'black', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
        // 센서
        {
          id: 'sensor',
          type: 'rect',
          elementDrawInfo: { width: 0, height: 0, color: '', opacity: 1 },
          textStyleInfo: {
            color: '',
          },
        },
      ],
    },
    positionInfo: {
      svgPlaceList: [
        {
          placeId: 'salternBlock',
          defList: [
            {
              id: 'SEB_1',
              name: '증발지_1',
              resourceId: 'solarEvaporationBlock',
              point: [200, 2560],
            },
            {
              id: 'SEB_2',
              name: '증발지_2',
              resourceId: 'solarEvaporationBlock',
              point: [460, 2560],
            },
            {
              id: 'SEB_3',
              name: '증발지_3',
              resourceId: 'solarEvaporationBlock',
              point: [730, 2560],
            },
            {
              id: 'SEB_4',
              name: '증발지_4',
              resourceId: 'solarEvaporationBlock',
              point: [1000, 2560],
            },
            {
              id: 'SEB_5',
              name: '증발지_5',
              resourceId: 'solarEvaporationBlock',
              point: [1270, 2560],
            },
            {
              id: 'SEB_6',
              name: '증발지_6',
              resourceId: 'solarEvaporationBlock',
              point: [1540, 2560],
            },
            {
              id: 'SEB_7',
              name: '증발지_7',
              resourceId: 'solarEvaporationBlock',
              point: [1810, 2560],
            },
            {
              id: 'SEB_8',
              name: '증발지_8',
              resourceId: 'solarEvaporationBlock',
              point: [2080, 2560],
            },
            {
              id: 'NEB_1',
              name: '일반 증발지_1',
              resourceId: 'normalEvaporationBlock_A',
              point: [80, 560],
            },
            {
              id: 'NEB_2',
              name: '일반 증발지_2',
              resourceId: 'normalEvaporationBlock_B',
              point: [80, 1430],
            },
            {
              id: 'NCB',
              name: '결정지',
              resourceId: 'normalCrystalizingBlock',
              point: [80, 3345],
            },
          ],
        },
        {
          placeId: 'brineWarehouse',
          defList: [
            { id: 'BW_1', name: '해주_1', resourceId: 'brineWarehouse_A', point: [130, 2170] },
            { id: 'BW_2', name: '해주_2', resourceId: 'brineWarehouse_B', point: [860, 2170] },
            { id: 'BW_3', name: '해주_3', resourceId: 'brineWarehouse_C', point: [1380, 2170] },
            { id: 'BW_4', name: '해주_4', resourceId: 'brineWarehouse_C', point: [1710, 2170] },
            { id: 'BW_5', name: '해주_5', resourceId: 'brineWarehouse_D', point: [700, 3400] },
            { id: 'BW_6', name: '해주_6', resourceId: 'brineWarehouse_D', point: [1000, 3400] },
          ],
        },
        {
          placeId: 'reservoir',
          defList: [
            { id: 'RV_1', name: '저수조_1', resourceId: 'reservoir_A', point: [10, 170] },
            { id: 'RV_2', name: '저수조_2', resourceId: 'reservoir_B', point: [3490, 170] },
          ],
        },
        {
          placeId: 'sea',
          defList: [
            { id: 'SEA', name: '바다', resourceId: 'sea', point: [10, 0] },
            { id: 'JG', name: '자고', resourceId: 'jago', point: [2620, 170] },
          ],
        },
        {
          placeId: 'waterWay',
          defList: [
            {
              id: 'WW_001',
              name: '수로_001',
              resourceId: 'waterWay',
              point: [10, 520, 2850, 520],
            },
            {
              id: 'WW_002',
              name: '수로_002',
              resourceId: 'waterWay',
              point: [40, 530, 40, 4260],
            },
            {
              id: 'WW_003',
              name: '수로_003',
              resourceId: 'waterWay',
              point: [2820, 530, 2820, 4260],
            },
            {
              id: 'WW_004',
              name: '수로_004',
              resourceId: 'waterWay',
              point: [70, 2520, 2370, 2520],
            },
            {
              id: 'WW_005',
              name: '수로_005',
              resourceId: 'waterWay',
              point: [2340, 2490, 2340, 3280],
            },
            {
              id: 'WW_006',
              name: '수로_006',
              resourceId: 'waterWay',
              point: [70, 3305, 2840, 3305],
            },
            {
              id: 'WW_007',
              name: '수로_007',
              resourceId: 'waterWay',
              point: [20, 4230, 2840, 4230],
            },
            {
              id: 'WW_008',
              name: '수로_008',
              resourceId: 'peWaterWay',
              point: [70, 2100, 230, 2100],
            },
            {
              id: 'WW_009',
              name: '수로_009',
              resourceId: 'peWaterWay',
              point: [310, 2000, 310, 2100],
            },
            {
              id: 'WW_010',
              name: '수로_010',
              resourceId: 'peWaterWay',
              point: [310, 2100, 310, 2170],
            },
            {
              id: 'WW_011',
              name: '수로_011',
              resourceId: 'peWaterWay',
              point: [310, 2100, 1300, 2100],
            },
            {
              id: 'WW_012',
              name: '수로_012',
              resourceId: 'peWaterWay',
              point: [1320, 2000, 1320, 2100],
            },
            {
              id: 'WW_013',
              name: '수로_013',
              resourceId: 'peWaterWay',
              point: [1320, 2100, 1320, 2170],
            },
            {
              id: 'WW_014',
              name: '수로_014',
              resourceId: 'peWaterWay',
              point: [585, 3520, 650, 3520],
            },
            {
              id: 'WW_015',
              name: '수로_015',
              resourceId: 'peWaterWay',
              point: [650, 3520, 730, 3520],
            },
            {
              id: 'WW_016',
              name: '수로_016',
              resourceId: 'peWaterWay',
              point: [640, 3545, 640, 3770],
            },
            {
              id: 'WW_017',
              name: '수로_017',
              resourceId: 'peWaterWay',
              point: [670, 3635, 1100, 3635],
            },
            {
              id: 'WW_018',
              name: '수로_018',
              resourceId: 'peWaterWay',
              point: [585, 3720, 650, 3720],
            },
            {
              id: 'WW_019',
              name: '수로_019',
              resourceId: 'peWaterWay',
              point: [640, 3750, 640, 4200],
            },
          ],
        },
        {
          placeId: 'pipeLine',
          defList: [
            // 주황
            {
              id: 'PL_001',
              name: '파이프_001',
              resourceId: 'pipeLine_A',
              point: [1895, 450, 1895, 560],
            },
            {
              id: 'PL_002',
              name: '파이프_002',
              resourceId: 'pipeLine_A',
              point: [2780, 180, 2780, 100],
            },
            {
              id: 'PL_003',
              name: '파이프_003',
              resourceId: 'pipeLine_A',
              point: [3490, 430, 2610, 430],
            },
            {
              id: 'PL_004',
              name: '파이프_004',
              resourceId: 'pipeLine_A',
              point: [480, 2170, 480, 2030],
            },
            {
              id: 'PL_005',
              name: '파이프_005',
              resourceId: 'pipeLine_A',
              point: [950, 2370, 950, 2400],
            },
            {
              id: 'PL_006',
              name: '파이프_006',
              resourceId: 'pipeLine_A',
              point: [955, 2395, 360, 2395],
            },
            {
              id: 'PL_007',
              name: '파이프_007',
              resourceId: 'pipeLine_A',
              point: [365, 2390, 365, 2560],
            },
            {
              id: 'PL_008',
              name: '파이프_008',
              resourceId: 'pipeLine_A',
              point: [1030, 2370, 1030, 2420],
            },
            {
              id: 'PL_009',
              name: '파이프_009',
              resourceId: 'pipeLine_A',
              point: [1025, 2415, 620, 2415],
            },
            {
              id: 'PL_010',
              name: '파이프_010',
              resourceId: 'pipeLine_A',
              point: [625, 2410, 625, 2560],
            },
            {
              id: 'PL_011',
              name: '파이프_011',
              resourceId: 'pipeLine_A',
              point: [1105, 2370, 1105, 2440],
            },
            {
              id: 'PL_012',
              name: '파이프_012',
              resourceId: 'pipeLine_A',
              point: [1110, 2435, 875, 2435],
            },
            {
              id: 'PL_013',
              name: '파이프_013',
              resourceId: 'pipeLine_A',
              point: [880, 2435, 880, 2560],
            },
            {
              id: 'PL_014',
              name: '파이프_014',
              resourceId: 'pipeLine_A',
              point: [1185, 2370, 1185, 2390],
            },
            {
              id: 'PL_015',
              name: '파이프_015',
              resourceId: 'pipeLine_A',
              point: [1190, 2390, 1150, 2390],
            },
            {
              id: 'PL_016',
              name: '파이프_016',
              resourceId: 'pipeLine_A',
              point: [1155, 2390, 1155, 2560],
            },
            {
              id: 'PL_017',
              name: '파이프_017',
              resourceId: 'pipeLine_A',
              point: [1265, 2370, 1265, 2395],
            },
            {
              id: 'PL_018',
              name: '파이프_018',
              resourceId: 'pipeLine_A',
              point: [1265, 2390, 1300, 2390],
            },
            {
              id: 'PL_019',
              name: '파이프_019',
              resourceId: 'pipeLine_A',
              point: [1295, 2390, 1295, 2560],
            },
            {
              id: 'PL_020',
              name: '파이프_020',
              resourceId: 'pipeLine_A',
              point: [1410, 2370, 1410, 2470],
            },
            {
              id: 'PL_021',
              name: '파이프_021',
              resourceId: 'pipeLine_A',
              point: [1405, 2470, 1570, 2470],
            },
            {
              id: 'PL_022',
              name: '파이프_022',
              resourceId: 'pipeLine_A',
              point: [1565, 2470, 1565, 2560],
            },
            {
              id: 'PL_023',
              name: '파이프_023',
              resourceId: 'pipeLine_A',
              point: [1490, 2370, 1490, 2450],
            },
            {
              id: 'PL_024',
              name: '파이프_024',
              resourceId: 'pipeLine_A',
              point: [1485, 2450, 1835, 2450],
            },
            {
              id: 'PL_025',
              name: '파이프_025',
              resourceId: 'pipeLine_A',
              point: [1830, 2450, 1830, 2560],
            },
            {
              id: 'PL_026',
              name: '파이프_026',
              resourceId: 'pipeLine_A',
              point: [1570, 2370, 1570, 2430],
            },
            {
              id: 'PL_027',
              name: '파이프_027',
              resourceId: 'pipeLine_A',
              point: [1565, 2430, 2120, 2430],
            },
            {
              id: 'PL_028',
              name: '파이프_028',
              resourceId: 'pipeLine_A',
              point: [2115, 2430, 2115, 2560],
            },
            {
              id: 'PL_029',
              name: '파이프_029',
              resourceId: 'pipeLine_C',
              point: [1760, 2370, 1760, 3370],
            },
            {
              id: 'PL_030',
              name: '파이프_030',
              resourceId: 'pipeLine_C',
              point: [1765, 3370, 950, 3370],
            },
            {
              id: 'PL_031',
              name: '파이프_031',
              resourceId: 'pipeLine_C',
              point: [955, 3370, 955, 3400],
            },
            {
              id: 'PL_032',
              name: '파이프_032',
              resourceId: 'pipeLine_C',
              point: [700, 3430, 580, 3430],
            },
            {
              id: 'PL_033',
              name: '파이프_033',
              resourceId: 'pipeLine_B',
              point: [1825, 2370, 1825, 2400],
            },
            {
              id: 'PL_034',
              name: '파이프_034',
              resourceId: 'pipeLine_B',
              point: [1830, 2395, 1710, 2395],
            },
            {
              id: 'PL_035',
              name: '파이프_035',
              resourceId: 'pipeLine_B',
              point: [1715, 2390, 1715, 2560],
            },
            {
              id: 'PL_036',
              name: '파이프_036',
              resourceId: 'pipeLine_B',
              point: [1890, 2370, 1890, 2410],
            },
            {
              id: 'PL_037',
              name: '파이프_037',
              resourceId: 'pipeLine_B',
              point: [1885, 2410, 1980, 2410],
            },
            {
              id: 'PL_038',
              name: '파이프_038',
              resourceId: 'pipeLine_B',
              point: [1985, 2405, 1985, 2560],
            },
            {
              id: 'PL_039',
              name: '파이프_039',
              resourceId: 'pipeLine_B',
              point: [1955, 2370, 1955, 2390],
            },
            {
              id: 'PL_040',
              name: '파이프_040',
              resourceId: 'pipeLine_B',
              point: [1950, 2390, 2260, 2390],
            },
            {
              id: 'PL_041',
              name: '파이프_041',
              resourceId: 'pipeLine_B',
              point: [2255, 2390, 2255, 2560],
            },
            {
              id: 'PL_045',
              name: '파이프_045',
              resourceId: 'pipeLine_D',
              point: [300, 2490, 2180, 2490],
            },
            {
              id: 'PL_046',
              name: '파이프_046',
              resourceId: 'pipeLine_D',
              point: [305, 2490, 305, 2560],
            },
            {
              id: 'PL_048',
              name: '파이프_048',
              resourceId: 'pipeLine_D',
              point: [305, 2490, 305, 2560],
            },
          ],
        },
      ],
      svgNodeList: [],
    },
  },
  setInfo: {
    mainInfo: { main_seq: 0, uuid: '' },
    dccConstructorList: [{}],
    dpcConstructorList: [{}],
    repeatNodeList: [{}],
    dataLoggerStructureList: [{}],
    // TODO: is_sensor 정리해야함
    nodeStructureList: [
      {
        target_id: 'temp',
        target_name: '온도',
        is_sensor: 1,
        data_unit: '℃',
        description: '섭씨',
        defList: [
          {
            target_id: 'moduleFrontTemperature',
            target_prefix: 'MFT',
            target_name: '모듈 앞면 온도',
            description: null,
            nodeList: [],
          },
          {
            target_id: 'moduleRearTemperature',
            target_prefix: 'MRT',
            target_name: '모듈 뒷면 온도',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '002', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '003', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '004', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '005', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '006', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '007', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'salinity',
        target_name: '염도',
        is_sensor: 1,
        data_unit: '%',
        description: null,
        defList: [
          {
            target_id: 'salinity',
            target_prefix: 'S',
            target_name: '염도',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '002', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '003', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '004', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '005', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '006', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '007', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'waterLevel',
        target_name: '수위',
        is_sensor: 1,
        data_unit: 'cm',
        description: null,
        defList: [
          {
            target_id: 'waterLevel',
            target_prefix: 'WL',
            target_name: '수위',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '002', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '003', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '004', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '005', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '006', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '007', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '010', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '011', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '012', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '013', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '014', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '015', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '016', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '017', axisScale: [0, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'waterDoor',
        target_name: '수문',
        is_sensor: 0,
        data_unit: null,
        description: null,
        defList: [
          {
            target_id: 'waterDoor',
            target_prefix: 'WD',
            target_name: '수문',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0, 1], moveScale: [2.4, 0.5] },
              { target_code: '002', axisScale: [0.5, 1], moveScale: [3.4, 0.5] },
              { target_code: '003', axisScale: [0, 1], moveScale: [2.4, 0] },
              { target_code: '004', axisScale: [0.5, 1], moveScale: [3.4, 0] },
              { target_code: '005', axisScale: [1, 0], moveScale: [0.65, -0.1] },
              { target_code: '006', axisScale: [0, 0], moveScale: [1.7, 0] },
              { target_code: '007', axisScale: [1, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [1, 0], moveScale: [0, 1.7] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 1] },
              { target_code: '010', axisScale: [1, 1], moveScale: [0, 0] },
              { target_code: '011', axisScale: [0, 1], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'valve',
        target_name: '밸브',
        is_sensor: 0,
        data_unit: null,
        description: null,
        defList: [
          {
            target_id: 'valve',
            target_prefix: 'V',
            target_name: '밸브',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0, 0], moveScale: [1, 0] },
              { target_code: '002', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '003', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '004', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '005', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '006', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '007', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '010', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '011', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '012', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '013', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '014', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '015', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '016', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '017', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '018', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '019', axisScale: [0, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'pump',
        target_name: '펌프',
        is_sensor: 0,
        data_unit: null,
        description: null,
        defList: [
          {
            target_id: 'pump',
            target_prefix: 'P',
            target_name: '펌프',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [0.7, 1], moveScale: [1, 0] },
              { target_code: '002', axisScale: [1, 0], moveScale: [0, 0] },
              { target_code: '003', axisScale: [0, 1], moveScale: [0, 0] },
              { target_code: '004', axisScale: [0.5, 0], moveScale: [0, 0] },
              { target_code: '005', axisScale: [0, 1], moveScale: [1, 0] },
              { target_code: '006', axisScale: [0, 1], moveScale: [2.3, 0] },
              { target_code: '007', axisScale: [0, 1], moveScale: [3.6, 0] },
              { target_code: '008', axisScale: [0, 1], moveScale: [4.9, 0] },
              { target_code: '009', axisScale: [0, 1], moveScale: [6.2, 0] },
              { target_code: '010', axisScale: [0, 1], moveScale: [0, 0] },
              { target_code: '011', axisScale: [0, 1], moveScale: [1.3, 0] },
              { target_code: '012', axisScale: [0, 1], moveScale: [2.6, 0] },
              { target_code: '013', axisScale: [0, 1], moveScale: [0.3, 0] },
              { target_code: '014', axisScale: [0, 1], moveScale: [1.4, 0] },
              { target_code: '015', axisScale: [0, 1], moveScale: [2.5, 0] },
              { target_code: '016', axisScale: [0, 1], moveScale: [3.6, 0] },
              { target_code: '017', axisScale: [0, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'outlet',
        target_name: '배출구',
        is_sensor: -1,
        save_db_type: NONE,
        data_unit: null,
        description: null,
        defList: [
          {
            target_id: 'outlet',
            target_prefix: 'O',
            target_name: '배출구',
            description: null,
            nodeList: [
              { target_code: '001', axisScale: [1, 1], moveScale: [0, -1.1] },
              { target_code: '002', axisScale: [1, 0], moveScale: [-4.1, 0] },
              { target_code: '003', axisScale: [0.2, 1], moveScale: [0.2, 0] },
              { target_code: '004', axisScale: [0, 1], moveScale: [1, 0] },
              { target_code: '005', axisScale: [1, 1], moveScale: [-1, 0] },
              { target_code: '006', axisScale: [1, 1], moveScale: [-3, 0] },
              { target_code: '007', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '010', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '011', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '012', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '013', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '014', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '015', axisScale: [1, 0], moveScale: [-0.9, 0] },
              { target_code: '016', axisScale: [1, 0], moveScale: [-0.9, 0] },
              { target_code: '017', axisScale: [1, 0], moveScale: [-1.5, 0] },
              { target_code: '018', axisScale: [1, 0], moveScale: [-1.3, 0] },
              { target_code: '019', axisScale: [0, 0], moveScale: [0.5, 0] },
              { target_code: '020', axisScale: [0, 0], moveScale: [0.5, 0] },
              { target_code: '021', axisScale: [1, 0], moveScale: [-0.5, 0] },
              { target_code: '022', axisScale: [0, 0], moveScale: [0.3, 0] },
              { target_code: '023', axisScale: [1, 0], moveScale: [-0.5, 0] },
              { target_code: '024', axisScale: [0, 0], moveScale: [1, 0] },
              { target_code: '025', axisScale: [1, 0], moveScale: [-0.5, 0] },
              { target_code: '026', axisScale: [1, 0], moveScale: [0, 3] },
              { target_code: '027', axisScale: [1, 0], moveScale: [-0.1, 0] },
            ],
          },
        ],
      },
    ],
  },
  relationInfo: {
    placeRelationList: [
      {
        target_id: 'salternBlock',
        target_name: '염판',
        description: null,
        defList: [
          {
            target_id: 'solarEvaporationBlock',
            target_prefix: 'SEB',
            target_name: '수중 태양광 발전 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: ['O_015'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: ['O_016'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '3',
                nodeList: ['O_017'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '4',
                nodeList: ['O_018'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '5',
                nodeList: ['O_019'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '6',
                nodeList: ['O_020', 'O_021'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '7',
                nodeList: ['O_022', 'O_023'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '8',
                nodeList: ['O_024', 'O_025'],
                depth: 0,
                place_info: {},
              },
            ],
          },
          {
            target_id: 'normalEvaporationBlock',
            target_prefix: 'NEB',
            target_name: '일반 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: ['WD_001', 'WD_002', 'O_002'],
                depth: 0,
              },
              {
                target_code: '2',
                nodeList: ['WD_001', 'WD_002', 'WD_003', 'WD_004', 'O_003'],
                depth: 0,
              },
            ],
          },
          {
            target_id: 'normalCrystalizingBlock',
            target_prefix: 'NCB',
            target_name: '일반 결정지',
            placeList: [
              {
                target_code: '',
                nodeList: ['WD_008', 'WD_010', 'O_026'],
                depth: 0,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'brineWarehouse',
        target_name: '해주',
        description: null,
        defList: [
          {
            target_id: 'brineWarehouse',
            target_prefix: 'BW',
            target_name: '해주',
            placeList: [
              {
                target_code: '1',
                nodeList: ['WD_006', 'P_004'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: ['P_005', 'P_006', 'P_007', 'P_008', 'P_009', 'WD_007', 'O_004'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '3',
                nodeList: ['P_010', 'P_011', 'P_012', 'O_005'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '4',
                nodeList: ['P_013', 'P_014', 'P_015', 'P_016', 'O_006'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '5',
                nodeList: ['WD_009', 'P_017', 'O_027'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '6',
                nodeList: [],
                depth: 0,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'reservoir',
        target_name: '저수조',
        description: null,
        defList: [
          {
            target_id: 'reservoir',
            target_prefix: 'RV',
            target_name: '저수조',
            placeList: [
              {
                target_code: '1',
                nodeList: ['P_001', 'O_001'],
                depth: 0,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: ['P_003'],
                depth: 0,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'sea',
        target_name: '바다',
        description: null,
        defList: [
          {
            target_id: 'sea',
            target_prefix: 'SEA',
            target_name: '바다',
            placeList: [
              {
                target_code: '',
                depth: 0,
                nodeList: [],
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'jago',
        target_name: '자고',
        description: null,
        defList: [
          {
            target_id: 'jago',
            target_prefix: 'JG',
            target_name: '자고',
            placeList: [
              {
                target_code: '',
                depth: 0,
                nodeList: ['P_002'],
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'waterWay',
        target_name: '수로',
        description: null,
        defList: [
          {
            target_id: 'waterWay',
            target_prefix: 'WW',
            target_name: '수로',
            placeList: [
              {
                target_code: '001',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '002',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '003',
                nodeList: [],
                depth: 0,
              },
              // TODO:
              {
                target_code: '004',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '005',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '006',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '007',
                nodeList: [],
                depth: 0,
              },
              {
                target_code: '008',
                nodeList: ['WD_005'],
                depth: 0,
              },
              {
                target_code: '009',
                nodeList: ['WD_003'],
                depth: 0,
              },
              {
                target_code: '010',
                nodeList: ['WD_006'],
                depth: 0,
              },
              {
                target_code: '011',
                nodeList: ['WD_005'],
                depth: 0,
              },
              {
                target_code: '012',
                nodeList: ['WD_004'],
                depth: 0,
              },
              {
                target_code: '013',
                nodeList: ['WD_007'],
                depth: 0,
              },
              {
                target_code: '014',
                nodeList: ['WD_008'],
                depth: 0,
              },
              {
                target_code: '015',
                nodeList: ['WD_009'],
                depth: 0,
              },
              {
                target_code: '016',
                nodeList: ['WD_011'],
                depth: 0,
              },
              {
                target_code: '017',
                nodeList: ['WD_010'],
                depth: 0,
              },
              {
                target_code: '018',
                nodeList: ['WD_011'],
                depth: 0,
              },
              {
                target_code: '019',
                nodeList: [],
                depth: 0,
              },
              // TODO: 센서류 작성 해야함
            ],
          },
        ],
      },
      {
        target_id: 'pipeLine',
        target_name: '파이프',
        description: null,
        defList: [
          {
            target_id: 'pipeLine',
            target_prefix: 'PL',
            target_name: '파이프',
            placeList: [
              // TODO:
              { target_code: '001', nodeList: ['P_001', 'O_002'] },
              { target_code: '002', nodeList: ['P_002'] },
              { target_code: '003', nodeList: ['P_003', 'O_001'] },
              { target_code: '004', nodeList: [] },
              { target_code: '005', nodeList: [] },
              { target_code: '006', nodeList: [] },
              { target_code: '007', nodeList: [] },
              { target_code: '008', nodeList: [] },
              { target_code: '009', nodeList: [] },
              { target_code: '010', nodeList: [] },
              { target_code: '011', nodeList: [] },
              { target_code: '012', nodeList: [] },
              { target_code: '013', nodeList: [] },
              { target_code: '014', nodeList: [] },
              { target_code: '015', nodeList: [] },
              { target_code: '016', nodeList: [] },
              { target_code: '017', nodeList: [] },
              { target_code: '018', nodeList: [] },
              { target_code: '019', nodeList: [] },
              { target_code: '020', nodeList: [] },
              { target_code: '021', nodeList: [] },
              { target_code: '022', nodeList: [] },
              { target_code: '023', nodeList: [] },
              { target_code: '024', nodeList: [] },
              { target_code: '025', nodeList: [] },
              { target_code: '026', nodeList: [] },
              { target_code: '027', nodeList: [] },
              { target_code: '028', nodeList: [] },
              { target_code: '029', nodeList: [] },
              { target_code: '030', nodeList: [] },
              { target_code: '031', nodeList: [] },
              { target_code: '032', nodeList: [] },
              { target_code: '033', nodeList: [] },
              { target_code: '034', nodeList: [] },
              { target_code: '035', nodeList: [] },
              { target_code: '036', nodeList: [] },
              { target_code: '037', nodeList: [] },
              { target_code: '038', nodeList: [] },
              { target_code: '039', nodeList: [] },
              { target_code: '040', nodeList: [] },
              { target_code: '041', nodeList: [] },
            ],
          },
        ],
      },
    ],
    smartSalternInfo: {
      pipeConnectionRelationList: [
        // TODO:
        { currNode: '', parentNodes: [], childNodes: [''] },
      ],
    },
    // FIXME: resourceId를 왜 list 처리했는지 모르겠다?
    svgResourceConnectionList: [
      {
        targetIdList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5', 'SEB_6', 'SEB_7', 'SEB_8'],
        resourceIdList: ['solarEvaporationBlock'],
      },
      {
        targetIdList: ['NEB_1'],
        resourceIdList: ['normalEvaporationBlock_A'],
      },
      {
        targetIdList: ['NEB_2'],
        resourceIdList: ['normalEvaporationBlock_B'],
      },
      {
        targetIdList: ['NCB'],
        resourceIdList: ['normalCrystalizingBlock'],
      },
      {
        targetIdList: ['RV_1'],
        resourceIdList: ['reservoir_A'],
      },
      {
        targetIdList: ['JG'],
        resourceIdList: ['jago'],
      },
      {
        targetIdList: ['RV_2'],
        resourceIdList: ['reservoir_B'],
      },
      {
        targetIdList: ['BW_1'],
        resourceIdList: ['brineWarehouse_A'],
      },
      {
        targetIdList: ['BW_2'],
        resourceIdList: ['brineWarehouse_B'],
      },
      {
        targetIdList: ['BW_3', 'BW_4'],
        resourceIdList: ['brineWarehouse_C'],
      },
      {
        targetIdList: ['BW_5', 'BW_6'],
        resourceIdList: ['brineWarehouse_D'],
      },
      // 회색수로
      {
        targetIdList: ['WW_001', 'WW_002', 'WW_003', 'WW_004', 'WW_005', 'WW_006', 'WW_007'],
        resourceIdList: ['waterWay'],
      },
      // pe 수로
      {
        targetIdList: [
          'WW_008',
          'WW_009',
          'WW_010',
          'WW_011',
          'WW_012',
          'WW_013',
          'WW_014',
          'WW_015',
          'WW_016',
          'WW_017',
          'WW_018',
        ],
        resourceIdList: ['peWaterWay'],
      },
      // 파이프 주황
      {
        targetIdList: [
          'PL_001',
          'PL_002',
          'PL_003',
          'PL_004',
          'PL_005',
          'PL_006',
          'PL_007',
          'PL_008',
          'PL_009',
          'PL_010',
          'PL_011',
          'PL_012',
          'PL_013',
          'PL_014',
          'PL_015',
          'PL_016',
          'PL_017',
          'PL_018',
          'PL_019',
          'PL_020',
          'PL_021',
          'PL_022',
          'PL_023',
          'PL_024',
          'PL_025',
          'PL_026',
          'PL_027',
          'PL_028',
        ],
        resourceIdList: ['pipeLine_A'],
      },
      // 파이프 파랑
      {
        targetIdList: [
          'PL_029',
          'PL_030',
          'PL_031',
          'PL_032',
          'PL_033',
          'PL_034',
          'PL_035',
          'PL_036',
          'PL_037',
        ],
        resourceIdList: ['pipeLine_B'],
      },
      // 파이프 갈색
      {
        targetIdList: ['PL_038', 'PL_039', 'PL_040', 'PL_041'],
        resourceIdList: ['pipeLine_C'],
      },
      // 빨강 갈색
      // FIXME: 수로로 할 것인가 파이프로 할것인가..
      {
        targetIdList: [
          'PL_042',
          'PL_043',
          'PL_044',
          'PL_045',
          'PL_046',
          'PL_047',
          'PL_048',
          'PL_049',
          'PL_050',
          'PL_051',
          'PL_052',
          'PL_053',
          'PL_054',
          'PL_055',
          'PL_056',
          'PL_057',
          'PL_058',
          'PL_059',
          'PL_060',
          'PL_061',
        ],
        resourceIdList: ['pipeLine_D'],
      },
      {
        targetIdList: [
          'V_001',
          'V_002',
          'V_003',
          'V_004',
          'V_005',
          'V_006',
          'V_007',
          'V_008',
          'V_009',
          'V_010',
          'V_011',
          'V_012',
          'V_013',
          'V_014',
          'V_015',
          'V_016',
          'V_017',
          'V_018',
          'V_019',
        ],
        resourceIdList: ['valve'],
      },
      // 수중 펌프
      {
        targetIdList: [
          'P_005',
          'P_006',
          'P_007',
          'P_008',
          'P_009',
          'P_010',
          'P_011',
          'P_012',
          'P_013',
          'P_014',
          'P_015',
          'P_016',
          'P_017',
        ],
        resourceIdList: ['underPump'],
      },
      // 양수 펌프
      {
        targetIdList: ['P_001', 'P_002', 'P_003', 'P_004'],
        resourceIdList: ['overPump'],
      },
      {
        targetIdList: [
          'WD_001',
          'WD_002',
          'WD_003',
          'WD_004',
          'WD_005',
          'WD_006',
          'WD_007',
          'WD_008',
          'WD_009',
          'WD_010',
          'WD_011',
        ],
        resourceIdList: ['waterDoor'],
      },
      {
        targetIdList: [
          'O_001',
          'O_002',
          'O_003',
          'O_004',
          'O_005',
          'O_006',
          'O_007',
          'O_008',
          'O_009',
          'O_010',
          'O_011',
          'O_012',
          'O_013',
          'O_014',
          'O_015',
          'O_016',
          'O_017',
          'O_018',
          'O_019',
          'O_020',
          'O_021',
          'O_022',
          'O_023',
          'O_024',
          'O_025',
          'O_026',
          'O_027',
          'O_028',
          'O_029',
        ],
        resourceIdList: ['output'],
      },
      // TODO: 센서 이미지 관계 나중에 잡아줘야함
    ],
    // FIXME:
    hiddenTextSvgModelResourceIdList: [],
  },
  controlInfo: {
    flowCmdList: [
      {
        srcPlaceId: '',
        destList: [
          {
            destPlaceId: '',
            trueNodeList: [],
            falseNodeList: [],
          },
        ],
      },
    ],
    setCmdList: [
      {
        cmdId: '',
        trueNodeList: [],
        falseNodeList: [],
      },
    ],
    tempControlList: [{ cmdName: '', trueList: [], falseList: [] }],
  },
};

module.exports = map;
