const {
  dcmConfigModel: {
    reqWrapCmdType: reqWCT,
    reqWrapCmdFormat: reqWCF,
    reqDeviceControlType: reqDCT,
    goalDataRange: goalDR,
    nodeDataType: { BLOCK, TROUBLE, NONE },
  },
} = require('../../../../../default-intelligence');

/**
 * @type {mDeviceMap}
 */
const map = {
  drawInfo: {
    frame: {
      mapInfo: {
        width: 3000,
        height: 2000,
        backgroundInfo: { backgroundData: '', backgroundPosition: [160, 0] },
      },
      svgModelResourceList: [
        {
          id: 'solarEvaporationBlock',
          type: 'rect',
          elementDrawInfo: { width: 80, height: 280, color: '#abe3e1', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalEvaporationBlock_A',
          type: 'rect',
          elementDrawInfo: { width: 700, height: 130, color: '#bd8f3a', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalEvaporationBlock_B',
          type: 'rect',
          elementDrawInfo: { width: 700, height: 100, color: '#bd8f3a', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalCrystalizingBlock',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 160, color: '#988224', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'reservoir_A',
          type: 'rect',
          elementDrawInfo: { width: 800, height: 90, color: 'blue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'reservoir_B',
          type: 'rect',
          elementDrawInfo: { width: 180, height: 90, color: 'blue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'drainage',
          type: 'rect',
          elementDrawInfo: { width: 80, height: 90, color: 'skyblue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_A',
          type: 'rect',
          elementDrawInfo: { width: 250, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_B',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_C',
          type: 'rect',
          elementDrawInfo: { width: 120, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_D',
          type: 'rect',
          elementDrawInfo: { width: 110, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'sea',
          type: 'rect',
          elementDrawInfo: { width: 1210, height: 20, color: 'skyblue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterWay',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#b2b2b2', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterWay_B',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#4c7a89', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'peWaterWay',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#108760', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'pipeLine_A',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#ff9a00', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'pipeLine_B',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#7513a1', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterDoor',
          type: 'rect',
          elementDrawInfo: {
            width: 30,
            height: 30,
            color: ['#a3a3a3', '#b45b95', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 5, leading: '1.8em' },
        },
        {
          id: 'gateValve',
          type: 'rect',
          elementDrawInfo: {
            width: 30,
            height: 30,
            color: ['#a3a3a3', 'yellow', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 4, leading: '2.5em' },
        },
        {
          id: 'overPump',
          type: 'circle',
          elementDrawInfo: {
            width: 35,
            height: 35,
            radius: 35,
            color: ['#a3a3a3', '#22fb00', '#dc1d1f'],
            opacity: 1,
            leading: '10em',
          },
          textStyleInfo: { color: '', fontSize: 6 },
        },
        {
          id: 'underPump',
          type: 'circle',
          elementDrawInfo: {
            width: 27,
            height: 27,
            radius: 27,
            color: ['#a3a3a3', '#8b24b0', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 6 },
        },
        {
          id: 'outlet',
          type: 'circle',
          elementDrawInfo: { width: 10, height: 10, radius: 10, color: 'black', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 8 },
        },
      ],
    },
    positionInfo: {
      svgPlaceList: [
        {
          placeId: 'salternBlock',
          defList: [
            {
              id: 'SEB_1',
              name: '증발지_1',
              resourceId: 'solarEvaporationBlock',
              point: [200, 640],
            },
            {
              id: 'SEB_2',
              name: '증발지_2',
              resourceId: 'solarEvaporationBlock',
              point: [305, 640],
            },
            {
              id: 'SEB_3',
              name: '증발지_3',
              resourceId: 'solarEvaporationBlock',
              point: [410, 640],
            },
            {
              id: 'SEB_4',
              name: '증발지_4',
              resourceId: 'solarEvaporationBlock',
              point: [520, 640],
            },
            {
              id: 'SEB_5',
              name: '증발지_5',
              resourceId: 'solarEvaporationBlock',
              point: [630, 640],
            },
            {
              id: 'SEB_6',
              name: '증발지_6',
              resourceId: 'solarEvaporationBlock',
              point: [740, 640],
            },
            {
              id: 'SEB_7',
              name: '증발지_7',
              resourceId: 'solarEvaporationBlock',
              point: [850, 640],
            },
            {
              id: 'SEB_8',
              name: '증발지_8',
              resourceId: 'solarEvaporationBlock',
              point: [960, 640],
            },
            {
              id: 'NEB_1',
              name: '일반 증발지_1',
              resourceId: 'normalEvaporationBlock_A',
              point: [200, 170],
            },
            {
              id: 'NEB_2',
              name: '일반 증발지_2',
              resourceId: 'normalEvaporationBlock_B',
              point: [200, 310],
            },
            { id: 'NCB', name: '결정지', resourceId: 'normalCrystalizingBlock', point: [200, 970] },
          ],
        },
        {
          placeId: 'brineWarehouse',
          defList: [
            { id: 'BW_1', name: '해주_1', resourceId: 'brineWarehouse_A', point: [200, 450] },
            { id: 'BW_2', name: '해주_2', resourceId: 'brineWarehouse_B', point: [460, 450] },
            { id: 'BW_3', name: '해주_3', resourceId: 'brineWarehouse_C', point: [670, 450] },
            { id: 'BW_4', name: '해주_4', resourceId: 'brineWarehouse_C', point: [800, 450] },
            { id: 'BW_5', name: '해주_5', resourceId: 'brineWarehouse_D', point: [445, 980] },
            { id: 'BW_6', name: '해주_6', resourceId: 'brineWarehouse_D', point: [570, 980] },
          ],
        },
        {
          placeId: 'reservoir',
          defList: [
            { id: 'RV_1', name: '저수지_1', resourceId: 'reservoir_A', point: [170, 40] },
            { id: 'RV_2', name: '저수지_2', resourceId: 'reservoir_B', point: [1200, 40] },
          ],
        },
        {
          placeId: 'sea',
          defList: [
            { id: 'SEA', name: '바다', resourceId: 'sea', point: [170, 10] },
            { id: 'D', name: '배수지', resourceId: 'drainage', point: [980, 40] },
          ],
        },
        {
          placeId: 'waterWay',
          defList: [
            {
              id: 'WW_001',
              name: '수로_001',
              resourceId: 'waterWay',
              point: [170, 155, 1163, 155],
            },
            {
              id: 'WW_002',
              name: '수로_002',
              resourceId: 'waterWay',
              point: [182, 160, 182, 1150],
            },
            {
              id: 'WW_003',
              name: '수로_003',
              resourceId: 'waterWay',
              point: [1150, 160, 1150, 1150],
            },
            {
              id: 'WW_004',
              name: '수로_004',
              resourceId: 'waterWay',
              point: [170, 610, 1090, 610],
            },
            {
              id: 'WW_005',
              name: '수로_005',
              resourceId: 'waterWay',
              point: [1075, 610, 1075, 950],
            },
            {
              id: 'WW_006',
              name: '수로_006',
              resourceId: 'waterWay',
              point: [170, 950, 1163, 950],
            },
            {
              id: 'WW_007',
              name: '수로_007',
              resourceId: 'waterWay',
              point: [170, 1150, 1163, 1150],
            },
            {
              id: 'WW_009',
              name: '수로_009',
              resourceId: 'peWaterWay',
              point: [435, 410, 435, 432],
            },
            {
              id: 'WW_010',
              name: '수로_010',
              resourceId: 'peWaterWay',
              point: [435, 432, 435, 450],
            },
            {
              id: 'WW_011',
              name: '수로_011',
              resourceId: 'peWaterWay',
              point: [435, 432, 475, 432],
            },
            {
              id: 'WW_012',
              name: '수로_012',
              resourceId: 'peWaterWay',
              point: [475, 410, 475, 432],
            },
            {
              id: 'WW_013',
              name: '수로_013',
              resourceId: 'peWaterWay',
              point: [475, 432, 475, 450],
            },
            {
              id: 'WW_014',
              name: '수로_014',
              resourceId: 'peWaterWay',
              point: [400, 1000, 425, 1000],
            },
            {
              id: 'WW_015',
              name: '수로_015',
              resourceId: 'peWaterWay',
              point: [425, 1000, 450, 1000],
            },
            {
              id: 'WW_016',
              name: '수로_016',
              resourceId: 'peWaterWay',
              point: [425, 1000, 425, 960],
            },
            {
              id: 'WW_017',
              name: '수로_017',
              resourceId: 'waterWay_B',
              point: [475, 530, 475, 570],
            },
            {
              id: 'WW_018',
              name: '수로_018',
              resourceId: 'waterWay_B',
              point: [775, 530, 775, 570],
            },
            {
              id: 'WW_019',
              name: '수로_019',
              resourceId: 'waterWay_B',
              point: [870, 530, 870, 570],
            },
            {
              id: 'WW_020',
              name: '수로_020',
              resourceId: 'waterWay_B',
              point: [230, 570, 1000, 570],
            },
            {
              id: 'WW_021',
              name: '수로_021',
              resourceId: 'waterWay_B',
              point: [242, 565, 242, 640],
            },
            {
              id: 'WW_022',
              name: '수로_022',
              resourceId: 'waterWay_B',
              point: [250, 610, 300, 610],
            },
            {
              id: 'WW_023',
              name: '수로_023',
              resourceId: 'waterWay_B',
              point: [340, 565, 340, 640],
            },
            {
              id: 'WW_024',
              name: '수로_024',
              resourceId: 'waterWay_B',
              point: [350, 610, 410, 610],
            },
            {
              id: 'WW_025',
              name: '수로_025',
              resourceId: 'waterWay_B',
              point: [438, 565, 438, 640],
            },
            {
              id: 'WW_026',
              name: '수로_026',
              resourceId: 'waterWay_B',
              point: [450, 610, 510, 610],
            },
            {
              id: 'WW_027',
              name: '수로_027',
              resourceId: 'waterWay_B',
              point: [555, 565, 555, 640],
            },
            {
              id: 'WW_028',
              name: '수로_028',
              resourceId: 'waterWay_B',
              point: [560, 610, 620, 610],
            },
            {
              id: 'WW_029',
              name: '수로_029',
              resourceId: 'waterWay_B',
              point: [665, 565, 665, 640],
            },
            {
              id: 'WW_030',
              name: '수로_030',
              resourceId: 'waterWay_B',
              point: [670, 610, 720, 610],
            },
            {
              id: 'WW_031',
              name: '수로_031',
              resourceId: 'waterWay_B',
              point: [780, 565, 780, 640],
            },
            {
              id: 'WW_032',
              name: '수로_032',
              resourceId: 'waterWay_B',
              point: [795, 610, 825, 610],
            },
            {
              id: 'WW_033',
              name: '수로_033',
              resourceId: 'waterWay_B',
              point: [890, 565, 890, 640],
            },
            {
              id: 'WW_034',
              name: '수로_034',
              resourceId: 'waterWay_B',
              point: [895, 610, 950, 610],
            },
            {
              id: 'WW_035',
              name: '수로_035',
              resourceId: 'waterWay_B',
              point: [1000, 565, 1000, 640],
            },
            {
              id: 'WW_036',
              name: '수로_036',
              resourceId: 'waterWay_B',
              point: [1010, 610, 1060, 610],
            },
          ],
        },
        {
          placeId: 'pipeLine',
          defList: [
            { id: 'PL_003', name: '파이프_003', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_004', name: '파이프_004', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_005', name: '파이프_005', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_006', name: '파이프_006', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_007', name: '파이프_007', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_008', name: '파이프_008', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_009', name: '파이프_009', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_010', name: '파이프_010', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_011', name: '파이프_011', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_012', name: '파이프_012', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_013', name: '파이프_013', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_014', name: '파이프_014', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_015', name: '파이프_015', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_016', name: '파이프_016', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_017', name: '파이프_017', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_018', name: '파이프_018', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_019', name: '파이프_019', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_020', name: '파이프_020', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_021', name: '파이프_021', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_022', name: '파이프_022', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_023', name: '파이프_023', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_024', name: '파이프_024', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_025', name: '파이프_025', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_026', name: '파이프_026', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_027', name: '파이프_027', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_028', name: '파이프_028', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_029', name: '파이프_029', resourceId: 'pipeLine_B', point: [0, 0, 0, 0] },
            { id: 'PL_030', name: '파이프_030', resourceId: 'pipeLine_B', point: [0, 0, 0, 0] },
            { id: 'PL_031', name: '파이프_031', resourceId: 'pipeLine_B', point: [0, 0, 0, 0] },
            { id: 'PL_032', name: '파이프_032', resourceId: 'pipeLine_B', point: [0, 0, 0, 0] },
            { id: 'PL_033', name: '파이프_033', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_034', name: '파이프_034', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
            { id: 'PL_035', name: '파이프_035', resourceId: 'pipeLine_A', point: [0, 0, 0, 0] },
          ],
        },
      ],
      svgNodeList: [],
    },
  },
  setInfo: {
    mainInfo: { main_seq: 2, uuid: 'bbbbb' },
    dccConstructorList: [
      {
        dccId: 'DCC_TEST_001',
        dccName: '테스트 용',
        connect_info: { type: 'socket', subType: '', host: 'localhost', port: 9000 },
      },
      {
        dccId: 'DCC_SSCS_001',
        dccName: '수중 태양광 장치 로거',
        connect_info: {
          type: 'zigbee',
          subType: 'xbee',
          baudRate: 9600,
          port: 'COM2',
          retryChance: 5,
        },
      },
      {
        dccId: 'DCC_CNT_001',
        dccName: '접속반 로거 A',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_002',
        dccName: '접속반 로거 B',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_003',
        dccName: '접속반 로거 C',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_004',
        dccName: '접속반 로거 D',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_IVT_001',
        dccName: '인버터 로거 A',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: { parser: 'delimiterParser', option: { type: 'Buffer', data: [4] } },
        },
      },
      {
        dccId: 'DCC_IVT_002',
        dccName: '인버터 로거 B',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: { parser: 'delimiterParser', option: { type: 'Buffer', data: [4] } },
        },
      },
      {
        dccId: 'DCC_IVT_003',
        dccName: '인버터 로거 C',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: { parser: 'delimiterParser', option: { type: 'Buffer', data: [4] } },
        },
      },
      {
        dccId: 'DCC_IVT_004',
        dccName: '인버터 로거 D',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: { parser: 'delimiterParser', option: { type: 'Buffer', data: [4] } },
        },
      },
    ],
    dpcConstructorList: [
      { dpcId: 'DPC_001', protocol_info: { mainCategory: 'UPSAS', subCategory: 'xbee' } },
      { dpcId: 'DPC_002', protocol_info: { mainCategory: 'UPSAS', subCategory: 'muan100kW' } },
      {
        dpcId: 'DPC_IVT_001',
        protocol_info: { mainCategory: 'Inverter', subCategory: 'hexPowerTriple' },
      },
      { dpcId: 'DPC_CNT_001', protocol_info: { mainCategory: 'Sensor', subCategory: 'CNT_dm_v1' } },
      {
        dpcId: 'DPC_CNT_002',
        protocol_info: { mainCategory: 'Sensor', subCategory: 'CNT_DK_v2.2' },
      },
    ],
    repeatNodeList: [
      {
        repeatId: 'RE_NODE_IVT',
        repeatCategory: 'node',
        nodeList: [
          { target_code: '001', target_name: '무안 100kW A (25kW 급)' },
          { target_code: '002', target_name: '무안 100kW B (25kW 급)' },
          { target_code: '003', target_name: '무안 100kW C (25kW 급)' },
          { target_code: '004', target_name: '무안 100kW D (25kW 급)' },
        ],
      },
      {
        repeatId: 'RE_PREFIX_IVT',
        repeatCategory: 'prefix',
        nodeList: [
          'IVT_PV_V',
          'IVT_PV_A',
          'IVT_PV_KW',
          'IVT_G_RS_V',
          'IVT_G_ST_V',
          'IVT_G_TR_V',
          'IVT_G_R_A',
          'IVT_G_S_A',
          'IVT_G_T_A',
          'IVT_G_L_F',
          'IVT_PW_PV_KW',
          'IVT_PW_G_KW',
          'IVT_PW_C_KWH',
          'IVT_TRB',
        ],
      },
      {
        repeatId: 'RE_NODE_CNT',
        repeatCategory: 'node',
        nodeList: [
          { target_code: '001', target_name: '무안 100kW A (25kW 급)' },
          { target_code: '002', target_name: '무안 100kW B (25kW 급)' },
          { target_code: '003', target_name: '무안 100kW C (25kW 급)' },
          { target_code: '004', target_name: '무안 100kW D (25kW 급)' },
        ],
      },
      {
        repeatId: 'RE_PREFIX_CNT',
        repeatCategory: 'prefix',
        nodeList: [
          'CNT_A_1CH',
          'CNT_V_1CH',
          'CNT_A_2CH',
          'CNT_V_2CH',
          'CNT_A_3CH',
          'CNT_V_3CH',
          'CNT_A_4CH',
          'CNT_V_4CH',
          'CNT_A_5CH',
          'CNT_V_5CH',
          'CNT_A_6CH',
          'CNT_V_6CH',
        ],
      },
    ],
    dataLoggerStructureList: [
      {
        target_prefix: 'D_G',
        target_name: '수문 DL',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F70001',
            target_code: '001',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_001'],
          },
        ],
      },
      {
        target_prefix: 'D_GV',
        target_name: '게이트형 밸브',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F70106',
            target_code: '106',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['GV_106'],
          },
        ],
      },
      {
        target_prefix: 'D_P',
        target_name: '펌프 DL',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F72004',
            target_code: '004',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['P_004'],
          },
        ],
      },
      {
        target_prefix: 'D_IVT',
        target_name: '인버터 DL',
        dataLoggerDeviceList: [
          {
            target_name: 'A (25kW 급)',
            serial_number: '01',
            target_code: '001',
            dccId: 'DCC_IVT_001',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'B (25kW 급)',
            serial_number: '02',
            target_code: '002',
            dccId: 'DCC_IVT_002',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'C (25kW 급)',
            serial_number: '03',
            target_code: '003',
            dccId: 'DCC_IVT_003',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'D (25kW 급)',
            serial_number: '04',
            target_code: '004',
            dccId: 'DCC_IVT_004',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
        ],
      },
      {
        target_prefix: 'D_CNT',
        target_name: '접속반',
        dataLoggerDeviceList: [
          {
            serial_number: 1,
            target_code: '001',
            dccId: 'DCC_CNT_001',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 2,
            target_code: '002',
            dccId: 'DCC_CNT_002',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 3,
            target_code: '003',
            dccId: 'DCC_CNT_003',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 4,
            target_code: '004',
            dccId: 'DCC_CNT_004',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
        ],
      },
    ],
    nodeStructureList: [
      {
        target_id: 'waterDoor',
        target_name: '수문',
        is_sensor: 0,
        defList: [
          {
            target_id: 'waterDoor',
            target_prefix: 'WD',
            target_name: '수문',
            nodeList: [{ target_code: '001', axisScale: [0, 1], moveScale: [0, 0] }],
          },
        ],
      },
      {
        target_id: 'valve',
        target_name: '밸브',
        is_sensor: 0,
        defList: [
          {
            target_id: 'gateValve',
            target_prefix: 'GV',
            target_name: '수문 용 밸브',
            description: '파이프 관에 연결된 밸브, 직경 100A PVC 용 밸브',
            nodeList: [{ target_code: '106', axisScale: [1, 0], moveScale: [0, 0] }],
          },
        ],
      },
      {
        target_id: 'pump',
        target_name: '펌프',
        is_sensor: 0,
        defList: [
          {
            target_id: 'pump',
            target_prefix: 'P',
            target_name: '펌프',
            nodeList: [{ target_code: '004', axisScale: [0, 1], moveScale: [1.7, 0] }],
          },
        ],
      },
      {
        target_id: 'outlet',
        target_name: '배출구',
        is_sensor: -1,
        is_submit_api: 0,
        save_db_type: 'none',
        description: '펌프의 배수구를 표현하기 위한 SVG 용 Element',
        defList: [
          {
            target_id: 'outlet',
            target_prefix: 'O',
            target_name: '배출구',
            nodeList: [
              { target_code: '001', axisScale: [1, 1], moveScale: [-2, 0] },
              { target_code: '002', axisScale: [1, 0], moveScale: [-2.4, 0] },
              { target_code: '003', axisScale: [0.2, 1], moveScale: [3.5, 0] },
              { target_code: '004', axisScale: [1, 0], moveScale: [-1.2, 0] },
              { target_code: '005', axisScale: [1, 0], moveScale: [-1.2, 0] },
              { target_code: '006', axisScale: [1, 0], moveScale: [-1.8, 0] },
              { target_code: '007', axisScale: [1, 0], moveScale: [-1.7, 0] },
              { target_code: '008', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '009', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '010', axisScale: [0, 0], moveScale: [0.5, 0] },
              { target_code: '011', axisScale: [0, 0], moveScale: [1, 0] },
              { target_code: '012', axisScale: [1, 0.5], moveScale: [0, 1.2] },
              { target_code: '013', axisScale: [1, 0], moveScale: [-0.2, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'groundRelay',
        target_name: '지락 계전기',
        is_sensor: 1,
        defList: [
          {
            target_id: 'isConnectorGroundRelay',
            target_prefix: 'CGR',
            target_name: '접속반 지락 계전기',
            nodeList: [],
          },
        ],
      },
      {
        target_id: 'vol',
        target_name: '전압',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'block',
        data_unit: 'V',
        description: null,
        defList: [
          {
            target_id: 'volCh1',
            target_name: '접속반 1 CH 전압',
            target_prefix: 'CNT_V_1CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh2',
            target_name: '접속반 2 CH 전압',
            target_prefix: 'CNT_V_2CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh3',
            target_name: '접속반 3 CH 전압',
            target_prefix: 'CNT_V_3CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh4',
            target_name: '접속반 4 CH 전압',
            target_prefix: 'CNT_V_4CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh5',
            target_name: '접속반 5 CH 전압',
            target_prefix: 'CNT_V_5CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh6',
            target_name: '접속반 6 CH 전압',
            target_prefix: 'CNT_V_6CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'pvVol',
            target_name: '인버터 PV 전압',
            target_prefix: 'IVT_PV_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridRsVol',
            target_name: 'RS 선간 전압',
            target_prefix: 'IVT_G_RS_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridStVol',
            target_name: 'ST 선간 전압',
            target_prefix: 'IVT_G_ST_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridTrVol',
            target_name: 'TR 선간 전압',
            target_prefix: 'IVT_G_TR_V',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'amp',
        target_name: '전류',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'block',
        data_unit: 'A',
        description: null,
        defList: [
          {
            target_id: 'ampCh1',
            target_name: '접속반 1 CH 전류',
            target_prefix: 'CNT_A_1CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh2',
            target_name: '접속반 2 CH 전류',
            target_prefix: 'CNT_A_2CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh3',
            target_name: '접속반 3 CH 전류',
            target_prefix: 'CNT_A_3CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh4',
            target_name: '접속반 4 CH 전류',
            target_prefix: 'CNT_A_4CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh5',
            target_name: '접속반 5 CH 전류',
            target_prefix: 'CNT_A_5CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh6',
            target_name: '접속반 6 CH 전류',
            target_prefix: 'CNT_A_6CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'pvAmp',
            target_name: '인버터 PV 전류',
            target_prefix: 'IVT_PV_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridRAmp',
            target_name: '인버터 R상 전류',
            target_prefix: 'IVT_G_R_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridSAmp',
            target_name: '인버터 S상 전류',
            target_prefix: 'IVT_G_S_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridTAmp',
            target_name: '인버터 T상 전류',
            target_prefix: 'IVT_G_T_A',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'kW',
        target_name: '전력량',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'block',
        data_unit: 'kW',
        description: '1 킬로와트(기호 kW)는 1 초 동안의 1,000 줄(N·m)에 해당하는 일률의 SI 단위',
        defList: [
          {
            target_id: 'pvKw',
            target_name: '인버터 PV 출력',
            target_prefix: 'IVT_PV_KW',
            description: 'PV',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'powerGridKw',
            target_name: '인버터 현재 전력',
            target_prefix: 'IVT_PW_G_KW',
            description: 'Power',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'kWh',
        target_name: '전력량',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'block',
        data_unit: 'kWh',
        description: '시간당 에너지 단위, 1 kW의 일률로 1 시간 동안 하는 일의 양',
        defList: [
          {
            target_id: 'powerDailyKwh',
            target_name: '인버터 하루 발전량',
            target_prefix: 'IVT_PW_D_KWH',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'powerCpKwh',
            target_name: '인버터 누적 발전량',
            target_prefix: 'IVT_PW_C_KWH',
            description: 'Cumulative Power Generation',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'frequency',
        target_name: '주파수',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'block',
        data_unit: 'Hz',
        defList: [
          {
            target_id: 'gridLf',
            target_name: '계통 주파수',
            target_prefix: 'IVT_G_L_F',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'trouble',
        target_name: '오류 목록',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: 'trouble',
        description: '장치에서 보내오는 이상 데이터',
        defList: [
          {
            target_id: 'operTroubleList',
            target_name: '인버터 에러',
            target_prefix: 'IVT_TRB',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
    ],
  },
  relationInfo: {
    placeRelationList: [
      {
        target_id: 'inverter',
        target_name: '인버터',
        description: '인버터를 설치한 공간',
        defList: [
          {
            target_id: 'inverter',
            target_prefix: 'P_IVT',
            placeList: [
              {
                target_code: '001',
                target_name: 'SK 쏠라 (25kW 급)',
                chart_color: '#212529',
                chart_sort_rank: 1,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '002',
                target_name: '쏠라 테크 A (25kW 급)',
                chart_color: '#fcc2d7',
                chart_sort_rank: 2,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '003',
                target_name: '쏠라 테크 B (25kW 급)',
                chart_color: '#d0bfff',
                chart_sort_rank: 3,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '004',
                target_name: '쏠라 테크 C (25kW 급)',
                chart_color: '#99e9f2',
                chart_sort_rank: 4,
                repeatId: 'RE_PREFIX_IVT',
              },
            ],
          },
        ],
      },
      {
        target_id: 'connector',
        target_name: '접속반',
        defList: [
          {
            target_id: 'connector',
            target_prefix: 'P_CNT',
            placeList: [
              {
                target_code: '001',
                target_name: 'SK 쏠라 (25kW 급)',
                chart_sort_rank: 1,
                chart_color: '#212529',
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '002',
                target_name: '쏠라테크 A (25kW 급)',
                chart_color: '#fcc2d7',
                chart_sort_rank: 2,
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '003',
                target_name: '쏠라테크 B (25kW 급)',
                chart_color: '#d0bfff',
                chart_sort_rank: 3,
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '004',
                target_name: '쏠라테크 C (25kW 급)',
                chart_color: '#99e9f2',
                chart_sort_rank: 4,
                repeatId: 'RE_PREFIX_CNT',
              },
            ],
          },
        ],
      },
      {
        target_id: 'salternBlock',
        target_name: '염판',
        description: null,
        defList: [
          {
            target_id: 'solarEvaporationBlock',
            target_prefix: 'SEB',
            target_name: '수중 태양광 발전 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '3',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '4',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '5',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '6',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '7',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '8',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
            ],
          },
          {
            target_id: 'normalEvaporationBlock',
            target_prefix: 'NEB',
            target_name: '일반 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: [],
                depth: 5,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: [],
                depth: 4,
                place_info: {},
              },
            ],
          },
          {
            target_id: 'normalCrystalizingBlock',
            target_prefix: 'NCB',
            target_name: '일반 결정지',
            placeList: [
              {
                target_code: '',
                nodeList: [],
                depth: 0,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'brineWarehouse',
        target_name: '해주',
        description: null,
        defList: [
          {
            target_id: 'brineWarehouse',
            target_prefix: 'BW',
            target_name: '해주',
            placeList: [
              {
                target_code: '1',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: ['P_004'],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '3',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '4',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '5',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '6',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'reservoir',
        target_name: '저수지',
        description: null,
        defList: [
          {
            target_id: 'reservoir',
            target_prefix: 'RV',
            target_name: '저수지',
            placeList: [
              {
                target_code: '1',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
              {
                target_code: '2',
                nodeList: [],
                depth: -1,
                place_info: {},
              },
            ],
          },
        ],
      },
      {
        target_id: 'sea',
        target_name: '바다',
        description: null,
        defList: [
          {
            target_id: 'sea',
            target_prefix: 'SEA',
            target_name: '바다',
            placeList: [{ target_code: '', depth: -1, nodeList: [], place_info: {} }],
          },
        ],
      },
      {
        target_id: 'drainage',
        target_name: '배수지',
        description: null,
        defList: [
          {
            target_id: 'drainage',
            target_prefix: 'D',
            target_name: '배수지',
            placeList: [{ target_code: '', depth: -1, nodeList: [], place_info: {} }],
          },
        ],
      },
      {
        target_id: 'waterWay',
        target_name: '수로',
        description: null,
        defList: [
          {
            target_id: 'waterWay',
            target_prefix: 'WW',
            target_name: '수로',
            placeList: [
              { target_code: '001', nodeList: [], depth: 0.2 },
              { target_code: '002', nodeList: [], depth: 0.3 },
              { target_code: '003', nodeList: [], depth: 0.3 },
              { target_code: '004', nodeList: [], depth: 0.6 },
              { target_code: '005', nodeList: [], depth: 0.5 },
              { target_code: '006', nodeList: [], depth: 0.4 },
              { target_code: '007', nodeList: [], depth: 0.5 },
              { target_code: '009', nodeList: [], depth: 0.5 },
              { target_code: '010', nodeList: [], depth: 0.3 },
              { target_code: '011', nodeList: [], depth: 0.4 },
              { target_code: '012', nodeList: [], depth: 0.5 },
              { target_code: '013', nodeList: [], depth: 0.3 },
              { target_code: '014', nodeList: [], depth: 0.8 },
              { target_code: '015', nodeList: [], depth: 0.8 },
              { target_code: '016', nodeList: ['WD_001'], depth: 0.7 },
              { target_code: '017', nodeList: [], depth: 0.5 },
              { target_code: '018', nodeList: [], depth: 0.5 },
              { target_code: '019', nodeList: [], depth: 0.5 },
              { target_code: '020', nodeList: [], depth: 0.6 },
              { target_code: '021', nodeList: [], depth: 0.8 },
              { target_code: '022', nodeList: ['GV_106'], depth: 0.7 },
              { target_code: '023', nodeList: [], depth: 0.8 },
              { target_code: '024', nodeList: [], depth: 0.7 },
              { target_code: '025', nodeList: [], depth: 0.8 },
              { target_code: '026', nodeList: [], depth: 0.7 },
              { target_code: '027', nodeList: [], depth: 0.8 },
              { target_code: '028', nodeList: [], depth: 0.7 },
              { target_code: '029', nodeList: [], depth: 0.8 },
              { target_code: '030', nodeList: [], depth: 0.7 },
              { target_code: '031', nodeList: [], depth: 0.8 },
              { target_code: '032', nodeList: [], depth: 0.7 },
              { target_code: '033', nodeList: [], depth: 0.8 },
              { target_code: '034', nodeList: [], depth: 0.7 },
              { target_code: '035', nodeList: [], depth: 0.8 },
              { target_code: '036', nodeList: [], depth: 0.7 },
            ],
          },
        ],
      },
      {
        target_id: 'pipeLine',
        target_name: '파이프',
        description: null,
        defList: [
          {
            target_id: 'pipeLine',
            target_prefix: 'PL',
            target_name: '파이프',
            placeList: [
              { target_code: '003', nodeList: [] },
              { target_code: '004', nodeList: [] },
              { target_code: '005', nodeList: ['P_004'] },
              { target_code: '006', nodeList: [] },
              { target_code: '007', nodeList: [] },
              { target_code: '008', nodeList: [] },
              { target_code: '009', nodeList: [] },
              { target_code: '010', nodeList: [] },
              { target_code: '011', nodeList: [] },
              { target_code: '012', nodeList: [] },
              { target_code: '013', nodeList: [] },
              { target_code: '014', nodeList: [] },
              { target_code: '015', nodeList: [] },
              { target_code: '016', nodeList: [] },
              { target_code: '017', nodeList: [] },
              { target_code: '018', nodeList: [] },
              { target_code: '019', nodeList: [] },
              { target_code: '020', nodeList: [] },
              { target_code: '021', nodeList: [] },
              { target_code: '022', nodeList: [] },
              { target_code: '023', nodeList: [] },
              { target_code: '024', nodeList: [] },
              { target_code: '025', nodeList: [] },
              { target_code: '026', nodeList: [] },
              { target_code: '027', nodeList: [] },
              { target_code: '028', nodeList: [] },
              { target_code: '029', nodeList: [] },
              { target_code: '030', nodeList: [] },
              { target_code: '031', nodeList: [] },
              { target_code: '032', nodeList: [] },
              { target_code: '033', nodeList: [] },
              { target_code: '034', nodeList: [] },
              { target_code: '035', nodeList: [] },
            ],
          },
        ],
      },
    ],
    smartSalternInfo: {
      pipeConnectionRelationList: [{ currNode: 'P_004', parentNodes: [], childNodes: ['O_004'] }],
    },
    svgResourceConnectionList: [
      {
        targetIdList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5', 'SEB_6', 'SEB_7', 'SEB_8'],
        resourceIdList: ['solarEvaporationBlock'],
      },
      { targetIdList: ['NEB_1'], resourceIdList: ['normalEvaporationBlock_A'] },
      { targetIdList: ['NEB_2'], resourceIdList: ['normalEvaporationBlock_B'] },
      { targetIdList: ['NCB'], resourceIdList: ['normalCrystalizingBlock'] },
      { targetIdList: ['RV_1'], resourceIdList: ['reservoir_A'] },
      { targetIdList: ['RV_2'], resourceIdList: ['reservoir_B'] },
      { targetIdList: ['D'], resourceIdList: ['drainage'] },
      { targetIdList: ['BW_1'], resourceIdList: ['brineWarehouse_A'] },
      { targetIdList: ['BW_2'], resourceIdList: ['brineWarehouse_B'] },
      { targetIdList: ['BW_3', 'BW_4'], resourceIdList: ['brineWarehouse_C'] },
      { targetIdList: ['BW_5', 'BW_6'], resourceIdList: ['brineWarehouse_D'] },
      {
        targetIdList: ['WW_001', 'WW_002', 'WW_003', 'WW_004', 'WW_005', 'WW_006', 'WW_007'],
        resourceIdList: ['waterWay'],
      },
      {
        targetIdList: [
          'WW_008',
          'WW_009',
          'WW_010',
          'WW_011',
          'WW_012',
          'WW_013',
          'WW_014',
          'WW_015',
          'WW_016',
          'WW_017',
          'WW_018',
          'WW_019',
        ],
        resourceIdList: ['peWaterWay'],
      },
      {
        targetIdList: [
          'WW_020',
          'WW_021',
          'WW_022',
          'WW_023',
          'WW_024',
          'WW_025',
          'WW_026',
          'WW_027',
          'WW_028',
          'WW_029',
          'WW_030',
          'WW_031',
          'WW_032',
          'WW_033',
          'WW_034',
          'WW_035',
          'WW_036',
        ],
        resourceIdList: ['waterWay_B'],
      },
      {
        targetIdList: [
          'PL_003',
          'PL_004',
          'PL_005',
          'PL_006',
          'PL_007',
          'PL_008',
          'PL_009',
          'PL_010',
          'PL_011',
          'PL_012',
          'PL_013',
          'PL_014',
          'PL_015',
          'PL_016',
          'PL_017',
          'PL_018',
          'PL_019',
          'PL_020',
          'PL_021',
          'PL_022',
          'PL_023',
          'PL_024',
          'PL_025',
          'PL_026',
          'PL_027',
          'PL_028',
          'PL_032',
          'PL_033',
          'PL_034',
          'PL_035',
        ],
        resourceIdList: ['pipeLine_A'],
      },
      { targetIdList: ['PL_029', 'PL_030', 'PL_031'], resourceIdList: ['pipeLine_B'] },
      {
        targetIdList: ['P_004'],
        resourceIdList: ['underPump'],
      },
      {
        targetIdList: ['GV_106'],
        resourceIdList: ['gateValve'],
      },
      {
        targetIdList: ['WD_001'],
        resourceIdList: ['waterDoor'],
      },
      {
        targetIdList: [
          'O_001',
          'O_002',
          'O_003',
          'O_004',
          'O_005',
          'O_006',
          'O_007',
          'O_008',
          'O_009',
          'O_010',
          'O_011',
          'O_012',
          'O_013',
        ],
        resourceIdList: ['outlet'],
      },
    ],
    hiddenTextSvgModelResourceIdList: ['pipeLine', 'outlet', 'waterWay'],
  },
  controlInfo: {
    flowCmdList: [
      {
        srcPlaceId: 'RV_1',
        destList: [
          {
            destPlaceId: 'NEB_1',
            trueNodeList: [],
            falseNodeList: ['WD_001'],
          },
        ],
      },
      {
        srcPlaceId: 'RV_2',
        destList: [{ destPlaceId: 'RV_1', trueNodeList: [], falseNodeList: [] }],
      },
      {
        srcPlaceId: 'NEB_1',
        destList: [
          {
            destPlaceId: 'NEB_2',
            trueNodeList: [],
            falseNodeList: ['WD_001'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['WD_001'], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'NEB_2',
        destList: [
          { destPlaceId: 'BW_1', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'BW_2', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_1',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: ['GV_106'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: ['GV_106'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_106'], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_2',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_3',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_4',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_5',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_6',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_7',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'SEB_8',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: [],
            falseNodeList: [],
          },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'NCB',
        destList: [
          { destPlaceId: 'BW_5', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEA', trueNodeList: [], falseNodeList: [] },
        ],
      },
      {
        srcPlaceId: 'BW_1',
        destList: [
          {
            destPlaceId: 'NEB_2',
            trueNodeList: [],
            falseNodeList: [],
          },
        ],
      },
      {
        srcPlaceId: 'BW_2',
        destList: [
          { destPlaceId: 'SEB_1', trueNodeList: ['P_004'], falseNodeList: ['GV_106'] },
          { destPlaceId: 'SEB_2', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEB_3', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEB_4', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEB_5', trueNodeList: [], falseNodeList: [] },
          {
            destPlaceId: 'SEB_ONE',
            destPlaceName: '수중 태양광 증발지 그룹 1',
            trueNodeList: ['P_004'],
            falseNodeList: ['GV_106'],
          },
        ],
      },
      {
        srcPlaceId: 'BW_3',
        destList: [
          { destPlaceId: 'SEB_6', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEB_7', trueNodeList: [], falseNodeList: [] },
          { destPlaceId: 'SEB_8', trueNodeList: [], falseNodeList: [] },
          {
            destPlaceId: 'SEB_TWO',
            destPlaceName: '수중 태양광 증발지 그룹 2',
            trueNodeList: [],
            falseNodeList: [],
          },
        ],
      },
      {
        srcPlaceId: 'BW_4',
        destList: [{ destPlaceId: 'BW_5', trueNodeList: [], falseNodeList: [] }],
      },
      {
        srcPlaceId: 'BW_5',
        destList: [{ destPlaceId: 'NCB', trueNodeList: [], falseNodeList: [] }],
      },
      {
        srcPlaceId: 'SEB_ONE',
        srcPlaceName: '수중 태양광 증발지 그룹 1',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: [],
            falseNodeList: ['GV_106'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: ['GV_106'],
          },
          {
            destPlaceId: 'SEA',
            trueNodeList: ['GV_106'],
            falseNodeList: [],
          },
        ],
      },
      {
        srcPlaceId: 'SEB_TWO',
        srcPlaceName: '수중 태양광 증발지 그룹 2',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: [],
            falseNodeList: [],
          },
          {
            destPlaceId: 'SEA',
            trueNodeList: [],
            falseNodeList: [],
          },
        ],
      },
    ],
    setCmdList: [
      {
        cmdId: 'closeAllDevice',
        trueNodeList: [],
        falseNodeList: ['GV_106', 'WD_001', 'P_004'],
      },
      {
        cmdId: 'rainMode',
        trueNodeList: ['GV_106', 'WD_001'],
        falseNodeList: ['P_004'],
      },
    ],
    scenarioCmdList: [
      {
        scenarioId: 'rainMode',
        scenarioList: [
          { wrapCmdFormat: 'SET', wrapCmdType: 'CONTROL', setCmdId: 'closeAllDevice' },
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: {
                  goalDataList: [],
                },
                flowSrcPlaceId: 'NCB',
                flowDestPlaceId: 'BW_5',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                flowSrcPlaceId: 'NCB',
                flowDestPlaceId: 'SEA',
              },
            ],
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: {
                  goalDataList: [],
                },
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'BW_3',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'SEA',
              },
            ],
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: {
                  goalDataList: [],
                },
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'BW_2',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'SEA',
              },
            ],
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: {
                  goalDataList: [],
                },
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'BW_1',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'SEA',
              },
            ],
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              flowSrcPlaceId: 'NEB_1',
              flowDestPlaceId: 'SEA',
            },
          ],
          { wrapCmdFormat: 'SET', wrapCmdType: 'CONTROL', setCmdId: 'rainMode' },
        ],
      },
      {
        scenarioId: 'normalFlowScenario',
        scenarioList: [
          { wrapCmdFormat: 'SET', wrapCmdType: 'CONTROL', setCmdId: 'closeAllDevice' },
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'RV_2',
                flowDestPlaceId: 'RV_1',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'RV_2',
                flowDestPlaceId: 'RV_1',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'BW_2',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'BW_2',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_2',
                flowDestPlaceId: 'SEB_ONE',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_2',
                flowDestPlaceId: 'SEB_ONE',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'BW_3',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'BW_3',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_3',
                flowDestPlaceId: 'SEB_TWO',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_3',
                flowDestPlaceId: 'SEB_TWO',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'BW_4',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'BW_4',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_4',
                flowDestPlaceId: 'BW_5',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'BW_4',
                flowDestPlaceId: 'BW_5',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_5',
                flowDestPlaceId: 'NCB',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'BW_5',
                flowDestPlaceId: 'NCB',
              },
            ],
          ],
        ],
      },
    ],
    tempControlList: [{ cmdName: '', trueList: [], falseList: [] }],
  },
};

module.exports = map;
